
for i in range(10):
	if i==5:
		raise Exception("Se ha producido una excepci√≥n")
